version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: merman-db
    ports:
      - "5439:5432"
    environment:
      POSTGRES_USER: merman
      POSTGRES_PASSWORD: merman_password
      POSTGRES_DB: merman
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
